### PR TITLE
fix error: mapreduce/master_rpc.go:48: debug call has arguments but no

### PR DESCRIPTION
**Pull request by XiaochenCui**
formatting directives

### CODE REVIEW

**Comment by Mr-Dai** [comment]
Hi, XiaochenCui. First of all, thank you for the PR.

Unfortunately, the code you modified comes from the start code provided by MIT-6.824, and making the official start code better is not among the purpose of this repository. I would prefer leaving the start code untouched, as long as the code can pass the provided test cases.

Have you experienced any difficulty running the code, like compilation error or failed test cases? If it's not the case, this PR might not be merged.

**Comment by XiaochenCui** [comment]
Hi, Mr-Dai.

This problem was discovered after I upgraded to go1.11 some time ago.
The test code originally worked fine, but running the test script after upgrading to go1.11 will give an error: 
`../mapreduce/master_rpc.go:48: debug call has arguments but no formatting directives`
I then installed some other golang versions and performed extensive testing.
I found that running the test code under go1.8 and go1.10 would not give an error, so I guess it might be that go1.11 introduces a new grammar check, or go vet from it.
Then I found these links:
https://go-review.googlesource.com/c/go/+/20163
https://github.com/golang/go/issues/12294#issuecomment-134278126
Although I haven't figured out the specific operating mechanism of go vet, I am sure that the test code will report an error in go1.11 and later.

**Comment by XiaochenCui** [comment]
It's more elegant to achieve scheduling using default

**Comment by Mr-Dai** [comment]
Thank you for noticing. I haven't tested this code for a very long time. I will check the go1.11 problem later.

**Comment by XiaochenCui** [comment]
Your current code(mapreduce/schedule.go) is wrong. If the last few tasks fail, they will not be rejoined because you have already jumped out of the for looping.
The correct implementation should be this: https://github.com/XiaochenCui/mit6.824/blob/battle/src/mapreduce/schedule.go, which is not elegant enough, but it is correct, because we won't jump out of the for looping until all the tasks are successful.
The reason your code can pass the test case is because the fault of the test case is set in the middle of the program.
A little advice for you: I think that you should be as thoughtful as possible when writing a distributed system, and write as many test cases as possible. As far as I know, the number of lines of test code for some distributed systems is 100 times or more that of the theme program.

**Comment by Mr-Dai** [comment]
> If the last few tasks fail, they will not be rejoined because you have already jumped out of the for looping.

Care to shed some light? I failed to see how the code can exit the for loop before all tasks succeed.

**Pull request closed without merging**
